[project]
name = "aws-lambda-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.72",
    "pytest>=9.1.1",
    "pytest-cov>=6.0.0",
    "requests>=2.34.2",
]

[tool.pytest.ini_options]
testpaths = ["lambda_project/lambda_proj/tests"]
pythonpath = ["lambda_project/lambda_proj"]
